import shadow.standard@Error;
import shadow.io@Console;

class shadow.test@ExceptionTest
{
	nullable Error e;
	public throwException() => () {
		throw ExceptionA:create();
	}
	public main( String[] args ) => ( int ) {
		try {
			throwException();
		} catch (ExceptionA ex) {
			Console:instance.printLine("ExceptionA");
		} catch (ExceptionB ex) {
			Console:instance.printLine("ExceptionB");
		} catch (ExceptionC ex) {
			Console:instance.printLine("ExceptionC");
		//} finally {
			//Console:instance.printLine("finally");
		}
		return 0;
	}
}
