import shadow.standard@Error;
import shadow.io@Console;

class shadow.test@ExceptionTest
{
	nullable Error e;
	public throwException() => () {
		throw ExceptionA:create();
	}
	public main() => () {
		try {
			throwException();
		} catch (ExceptionA ex) {
			Console.printLine("ExceptionA");
		} finally {
			Console.printLine("finally");
		}
	}
}
